### ISSUE TITLE
PC Reservation is not being installed

### ISSUE THREAD

**Issue by lbodnyk-dcls-org** [DauphinCountyLibrarySystem/Deployment#13]
Staff version. Might be a bad command line. If so, how do we define the IP address? We might have to robocopy the config file over.

**Comment by Kramermp** [comment]
Staff office computer do not install PC Reservation, but Staff Front line Computers do install PC Reservation. If this is in reference to office computers then they need to add the call similar to the front line computers.

**Comment by Kramermp** [comment]
The Front Line computers seem to be installing this correctly.
