### ISSUE TITLE
Self-check role

### ISSUE THREAD

**Issue by lbodnyk-dcls-org** [DauphinCountyLibrarySystem/Deployment#14]
Like kiosk, but no install OneStop software.

**Comment by Faustthephantom** [comment]
Is kiosk in reference to catalog?

**Comment by Kramermp** [comment]
The self check role was added to the dropdown, but I did not fully implement the role. Instead, during main it checks if you selected the selfcheck role. If you did it will kick you out of the program.

**Comment by Kramermp** [comment]
The one sub install is not silent and needs a person to click that they want to install it.

**Comment by Kramermp** [comment]
You can now properly deploy Self-Check machines with properly configured files.

**Comment by Kramermp** [comment]
Needs to install Print release and PC Res

**Comment by Kramermp** [comment]
Now installs PC Res and LPTOne
