### ISSUE TITLE
Chrome Icon not on Desktop

### ISSUE THREAD

**Issue by lbodnyk-dcls-org** [DauphinCountyLibrarySystem/Deployment#15]

**Comment by Faustthephantom** [comment]
This issue should be found in Labels.ahk, in the method "__subSpecificTasks__". Is there a specific version of the build that we want this icon for?

**Comment by Faustthephantom** [comment]
Patron and Staff both have Chrome icon.

**Comment by Kramermp** [comment]
Front Line also receives the icon. I will mark this issue as closed, and assume it was fixed in an earlier build.
