### ISSUE TITLE
LogMeIn is installed before name is changed

### ISSUE THREAD

**Issue by lbodnyk-dcls-org** [DauphinCountyLibrarySystem/Deployment#17]
LogMeIn needs to wait until after the name is changed before it installs.

**Comment by Faustthephantom** [comment]
There is a fairly simple to this issue. By placing a compiled script in the Windows Startup file we can restart the computer and have it begin running the other script on startup. The file would then remove the script from the start up file on completion to prevent the script from running endlessly.

**Comment by Faustthephantom** [comment]
I've explored using either registry keys or the complied script method but both of these methods require the user to complete the  UAC command so it maybe easier to instead use Powershell to import a task to the task scheduler, that triggers Configure-Image again with command line arguments telling it that it has been restarted. This task would be triggered through user log on.

**Comment by Faustthephantom** [comment]
This issue should now be resolved.
